name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: onegymsolution.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t onegymsolution.azurecr.io/backend:${{ github.sha }} -f Dockerfile.dev .
        docker push onegymsolution.azurecr.io/backend:${{ github.sha }}